from pathlib import Path
import json
r=Path(__file__).resolve().parents[1]
data=json.loads((r/'data/HOST_ONLY/console_bundle.json').read_text())
js=(r/'tools/console.js').read_text()
html='''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; connect-src 'none'; img-src data:; base-uri 'none'; form-action 'none'">
<title>瞎掰王 · Who Really Knows? · Pilot v0.1</title>
<style>
:root{--ink:#172a3a;--muted:#536373;--line:#d5dee6;--paper:#f4f6f8;--accent:#14665c;--soft:#e5f2ee;--warn:#9b4b23}
*{box-sizing:border-box}body{margin:0;background:var(--paper);font-family:system-ui,-apple-system,"Segoe UI","Microsoft YaHei",sans-serif;color:var(--ink);line-height:1.6}header{background:var(--ink);color:white;padding:24px 4vw 21px}header .eyebrow{font-size:11px;letter-spacing:2.8px;color:#9de2cb}h1{font-size:27px;line-height:1.25;margin:7px 0}header p{color:#d1dae1;margin:6px 0 0;font-size:14px}.container{max-width:1540px;margin:auto;padding:20px 3vw}.warning{border-left:4px solid var(--warn);background:#fff4e9;padding:12px 16px;margin-bottom:18px;font-size:14px}.bar{display:flex;gap:12px;flex-wrap:wrap;align-items:end}.card{background:white;border:1px solid var(--line);border-radius:10px;padding:18px;margin-bottom:16px}label{font-size:13px;color:var(--muted);display:block}input[type=text],select,textarea{border:1px solid #bfcbd5;background:white;color:var(--ink);border-radius:5px;padding:9px;font:inherit;width:100%}input,select{font-size:14px}textarea{font-family:ui-monospace,Consolas,monospace;font-size:12px;line-height:1.55;resize:vertical}button,.filebutton{border:1px solid var(--line);border-radius:6px;padding:9px 13px;background:white;color:var(--ink);font:inherit;font-size:13px;cursor:pointer}button:hover{border-color:var(--accent)}button.primary{background:var(--accent);color:white;border-color:var(--accent)}button:disabled{opacity:.45;cursor:not-allowed}.grow{flex:1;min-width:220px}.small{font-size:12px;color:var(--muted)}.grid{display:grid;grid-template-columns:280px minmax(0,1fr);gap:18px;align-items:start}.step{width:100%;display:block;text-align:left;margin:0 0 7px;font-size:12px;padding:9px}.step.active{outline:2px solid var(--accent);background:var(--soft)}.step.done{border-left:4px solid var(--accent)}.sticky{position:sticky;top:16px}h2{font-size:20px;line-height:1.3;margin:0 0 6px}h3{font-size:15px;margin:0 0 10px}.badge{font-size:11px;background:var(--soft);color:var(--accent);border-radius:20px;padding:4px 10px}.split{display:grid;grid-template-columns:1fr 1fr;gap:14px}.fieldrow{display:flex;gap:10px;margin:10px 0;flex-wrap:wrap}.fieldrow>label{flex:1;min-width:150px}.flags{display:flex;flex-wrap:wrap;gap:8px 16px}.flags label{font-size:12px;color:var(--ink)}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px;max-height:400px;overflow:auto}summary{cursor:pointer;font-size:13px;font-weight:600}#target{color:var(--accent);font-weight:600;font-size:14px}#parseStatus{padding:10px;background:var(--paper);font-size:12px;min-height:44px}#copyNotice{min-height:22px}.footer{font-size:12px;color:var(--muted);padding:8px 0 25px}.topmeta{display:flex;justify-content:space-between;gap:10px;align-items:start}.nowrap{white-space:nowrap}@media(max-width:950px){.grid{grid-template-columns:1fr}.sticky{position:static}.split{grid-template-columns:1fr}#stepList{display:grid;grid-template-columns:1fr 1fr;gap:5px}.step{margin:0}}@media print{button,.filebutton,#stepList{display:none}.grid,.split{display:block}.sticky{position:static}}
</style></head><body>
<header><div class="eyebrow">WHO REALLY KNOWS? · OFFLINE RESEARCH PILOT</div><h1>瞎掰王 · 信息访问归因实验</h1><p>20 个正式案例 + 2 个练习案例 · 三轮质询 · 同对话的独立证据对照 · v0.1.0</p></header>
<div class="container"><div class="warning"><strong>主持人专用。</strong>此页面和整个 ZIP 含有完整答案，不能上传给被测模型。只复制“当前应发送的提示词”。本页不联网、不自动操作 Arena；每次模型调用都由你手动完成。先读 README.md。</div>
<section class="card"><h3>1. 固定两款实际可选模型</h3><div class="bar"><label class="grow">M1：界面完整名称<input id="model1" type="text" placeholder="原样抄录，不预设版本"></label><label class="grow">M2：界面完整名称<input id="model2" type="text" placeholder="原样抄录，不选 Max / Auto"></label><button id="applyModels" class="primary">应用到当前题 / 后续新题</button></div><p class="small">同一题两个 speaker 必须用同一模型、两个独立会话。R1 为 M1 → M2；R2 为 M2 → M1。不使用 Search / Agent，后台工具无法确认时记录 unknown。</p></section>
<section class="card"><div class="bar"><label class="grow">2. 选择案例<select id="caseSelect"></select></label><button id="exportOne" class="primary">导出本题 JSON</button><button id="exportAll">导出全部记录</button><label class="filebutton">导入 JSON<input id="importFile" type="file" accept=".json,application/json" hidden></label></div><p id="storageNotice" class="small"></p></section>
<div class="grid"><aside class="card sticky"><h3 id="progress">0 / 14</h3><p class="small">每一步只操作指定会话。N 与 E 必须各自新开。</p><nav id="stepList"></nav></aside><main>
<section class="card"><div class="topmeta"><div><h2 id="caseTitle"></h2><div id="configInfo" class="small"></div></div><span class="badge">本地 · 不发送数据</span></div>
<div class="fieldrow"><label>本题 speaker 完整模型名<input id="speakerModel" type="text"></label><label>本题 judge 完整模型名<input id="judgeModel" type="text"></label></div>
<div class="fieldrow"><label>界面模式<input id="mode" type="text" value="Direct"></label><label>Effort / 其他可见设置<input id="effort" type="text" value="unknown"></label><label>工具状态<select id="toolsStatus"><option value="not_verified">后台无法验证 / unknown</option><option value="no_tools_observed">未观察到工具调用</option><option value="disabled_verified">确有可核验关闭设置</option><option value="tool_use_observed">观察到了工具调用</option></select></label></div>
<details><summary>公共题卡（无答案）</summary><pre id="publicCard"></pre></details></section>
<section class="card"><div class="topmeta"><h2 id="stepTitle"></h2><span id="stepKey" class="badge"></span></div><p id="target"></p><div class="split"><div><label for="prompt">当前应发送的提示词</label><textarea id="prompt" rows="27" readonly></textarea><div class="fieldrow"><button id="copyPrompt" class="primary">复制并本地记录待发送文本</button></div><div id="copyNotice" class="small"></div></div><div><label for="rawReply">模型最终原始回复（完整保留）</label><textarea id="rawReply" rows="27" placeholder="在指定会话发送后，将最终回复完整粘贴到这里；不要替模型修改内容。"></textarea><p id="parseStatus"></p></div></div>
<div id="manualWrap" hidden><label>仅在格式失败时：原样提取上一轮明确提出的问题，不得自己编写<input id="manualQuestion" type="text" placeholder="正常时留空；手工提取会记录为 deviation"></label></div>
<div class="bar"><button id="prev">← 上一步</button><button id="next" class="primary">下一步 →</button></div></section>
<section class="card"><h3>偏离、状态与原始观察</h3><div id="flags" class="flags"></div><label style="margin-top:12px">笔记（不自动写入给模型的 prompt）<textarea id="notes" rows="4" placeholder="技术重试、异常对话、实际时间设置等。不要记录账户密码或认证 token。"></textarea></label><div class="fieldrow"><label>本题状态<select id="runStatus"><option value="not_started">not_started</option><option value="in_progress">in_progress</option><option value="completed">completed</option><option value="aborted">aborted</option></select></label></div><details><summary>主持人核验 · 建议完成所有判断后再展开</summary><p class="small">这会显示正确角色和三个核验结果，绝不能发送给裁判。</p><button id="showHost">显示核验分组</button><pre id="hostDiagnostic"></pre></details></section>
</main></div><div class="footer">无独立线索时，判断接近随机不自动说明模型缺陷。E 对照只在原始承诺确实区分双方的案例中具有明确诊断意义。浏览器缓存不代替备份；每题导出 JSON。此包尚无真实模型结果。</div></div>
<script>globalThis.PILOT_DATA = __DATA__;</script><script>__CODE__</script></body></html>'''
html=html.replace('__DATA__',json.dumps(data,ensure_ascii=False).replace('<','\\u003c')).replace('__CODE__',js.replace('</script','<\\/script'))
(r/'START_HERE.html').write_text(html,encoding='utf-8')
print('Offline HTML',len(html.encode()),'bytes')
