/* Freeze two prompts before dispatch; no browser or network calls. */
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const repo=path.resolve(__dirname,'..'),root=path.join(repo,'v0_3_h2');
if(fs.existsSync(path.join(root,'bundle.json')))throw Error('Frozen bundle exists; do not overwrite');
const source='v0_2_other/published_runs/arena_20261002_other_pairs01/logs/L01V1.json';
const record=JSON.parse(fs.readFileSync(path.join(repo,source),'utf8'));
const data=JSON.parse(fs.readFileSync(path.join(repo,'v0_2_other/bundle.json'),'utf8'));
const C=require(path.join(repo,'v0_2_other/console.js'));
const c=data.cases.find(c=>c.case_id==='L01V1');
const neutral=C.buildPrompt(data,c,record,'judge_N');
if(neutral!==record.sent_prompts.judge_N)throw Error('Historical neutral prompt mismatch');
const inventory='The ancestor has consonants /k g t d p b m l/ and vowels /i e a o u/.';
const notation='A dot marks a syllable boundary, the IPA stress mark ˈ immediately before a syllable marks that syllable as stressed, and # is a word boundary.';
const fixed='All listed forms and stress/syllable divisions are fixed inputs.';
const before=inventory+' '+notation+' '+fixed;
const after=notation+'\n\n'+fixed+'\n\n'+inventory;
if(c.public_text.split(before).length!==2)throw Error('Public block mismatch');
const salientPublic=c.public_text.replace(before,after);
const salient=C.buildPrompt(data,{...c,public_text:salientPublic},record,'judge_N');
const transcript=C.transcript(c,record,true);
const sha=s=>crypto.createHash('sha256').update(s).digest('hex');
const words=s=>s.split(/\s+/).filter(Boolean).sort();
if(JSON.stringify(words(c.public_text))!==JSON.stringify(words(salientPublic)))throw Error('Words changed');
if(neutral.replace(c.public_text,'<PUBLIC>')!==salient.replace(salientPublic,'<PUBLIC>'))throw Error('Non-public content changed');
fs.mkdirSync(root,{recursive:true});
const bundle={version:'0.3.0-h2-qualification01',frozen_utc:new Date().toISOString(),source,evidence_head:'c0f2d891ced947fc040f75af5514a2acadb0d8d2',case_id:'L01V1',informed_seat:'A',historical_p_A:0.1,model:'gemini-3.8-flash-high',mode:'Direct',send_order:['neutral','salient'],transcript,transcript_sha256:sha(transcript),source_sha256:sha(fs.readFileSync(path.join(repo,source),'utf8')),public_blocks:{before,after},arms:{neutral:{public_text:c.public_text,prompt:neutral,prompt_sha256:sha(neutral)},salient:{public_text:salientPublic,prompt:salient,prompt_sha256:sha(salient)}},metric:'delta = p_A_salient - p_A_neutral; predicted negative',decision:{neutral_replication_max_p_A:0.25,material_shift_absolute:0.1},limitations:['One fixed transcript and one fresh response per arm; sampling variability cannot be separated from presentation effects.','A boundary-description wording error remains unchanged.','No mechanistic or population causal claim.'],audit:{historical_neutral_exact:true,identical_transcript:true,identical_nonpublic_prompt:true,public_word_multiset_equal:true}};
fs.writeFileSync(path.join(root,'bundle.json'),JSON.stringify(bundle,null,2)+'\n');
for(const arm of bundle.send_order)fs.writeFileSync(path.join(root,arm+'_prompt.txt'),bundle.arms[arm].prompt);
console.log(JSON.stringify({frozen:bundle.version,bundle_sha256:sha(fs.readFileSync(path.join(root,'bundle.json'),'utf8')),audit:bundle.audit}));
